In [28]:
import requests
import pandas as pd
import alpaca_trade_api as tradeapi
import json
from dotenv import load_dotenv
import os

In [29]:
load_dotenv ()

True

In [30]:
api_key = os.getenv("ALPACA_API_KEY")
alpaca_secret_key = os.getenv("ALPACA_SECRET_KEY")

api = tradeapi.REST(
    api_key,
    alpaca_secret_key,
    api_version="v2"
)

In [31]:
# Set timeframe to '1D'
timeframe = "1D"

In [32]:
start_date = pd.Timestamp("2020-01-01", tz="America/Chicago").isoformat()
end_date = pd.Timestamp("2020-9-14", tz="America/Chicago").isoformat()

In [33]:
# Set the stock tickers
tickers = ["SPY", "LUV", "DIS", "AAPL", "SBUX", "WORK"]

In [34]:
# Get 1 year's worth of historical data for all stocks
df_ticker = api.get_barset(
    tickers,
    timeframe,
    start=start_date,
    end=end_date,
).df

In [36]:
# Display sample data
df_ticker.head()

                             AAPL                                       \
                             open      high      low   close    volume
2020-01-02 00:00:00-05:00  296.24  300.6000  295.190  300.58  30589026
2020-01-03 00:00:00-05:00  297.15  300.5800  296.500  297.38  31609363
2020-01-06 00:00:00-05:00  293.79  299.9600  292.750  299.78  27487207
2020-01-07 00:00:00-05:00  299.84  300.9000  297.480  298.27  24353387
2020-01-08 00:00:00-05:00  297.16  304.4399  297.156  303.15  28984028

                              DIS                                       ...  \
                             open      high       low   close   volume  ...
2020-01-02 00:00:00-05:00  145.29  148.2000  145.1000  148.18  8086298  ...
2020-01-03 00:00:00-05:00  146.40  147.9000  146.0549  146.48  5618868  ...
2020-01-06 00:00:00-05:00  145.54  146.0300  144.3100  145.65  7363097  ...
2020-01-07 00:00:00-05:00  145.99  146.8699  145.4200  145.68  5725258  ...
2020-01-08 00:00:00-05:00  145.49  146.1300  144.8200  145.45  5742454  ...

                              SPY                                     WORK  \
                             open    high     low   close    volume   open
2020-01-02 00:00:00-05:00  323.54  324.85  322.53  324.85  45862759  22.32
2020-01-03 00:00:00-05:00  321.16  323.64  321.10  322.44  55090099  22.50
2020-01-06 00:00:00-05:00  320.48  323.73  320.36  323.67  41271531  22.32
2020-01-07 00:00:00-05:00  323.02  323.54  322.24  322.73  33333873  23.53
2020-01-08 00:00:00-05:00  322.94  325.78  322.69  324.42  53033838  23.61


                            high      low    close    volume
2020-01-02 00:00:00-05:00  23.16  22.1400  23.0200  11241313
2020-01-03 00:00:00-05:00  22.92  22.3803  22.4600   6300110
2020-01-06 00:00:00-05:00  23.66  22.1600  23.5250  11773679
2020-01-07 00:00:00-05:00  23.95  23.2200  23.8200   9560819
2020-01-08 00:00:00-05:00  24.26  23.2500  23.7645   6991680

[5 rows x 30 columns]