In [140]:
# Import libraries and dependencies
import os
import requests
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
from dotenv import load_dotenv
import alpaca_trade_api as tradeapi
import datetime 

%matplotlib inline

In [141]:
# Load .env enviroment variables
from dotenv import load_dotenv
load_dotenv()

# Set Alpaca API key and secret
alpaca_api_key = os.getenv("ALPACA_API_KEY")
alpaca_secret_key = os.getenv("ALPACA_SECRET_KEY")

# Create an object for aplpaca api 
api = tradeapi.REST(
    alpaca_api_key,
    alpaca_secret_key,
    api_version = "v2"
)

In [154]:
sectors_csv = Path("Resources/spy_etf_sectors.csv")
sectors_df = pd.read_csv(sectors_csv)

sectors_df = sectors_df.drop(columns=["Zacks\nG Sector", "\nCompany", "% of\nPortfolio"])

sectors_df = sectors_df.rename(columns={
    "\nTicker": "ticker",
    "Russell\nSector": "sector"
})
sectors_df

    ticker      sector
0     ATVI  TECHNOLOGY
1    GOOGL  TECHNOLOGY
2     GOOG  TECHNOLOGY
3        T   UTILITIES
4      CTL   UTILITIES
..     ...         ...
499    PEG   UTILITIES
500    SRE   UTILITIES
501     SO   UTILITIES
502    WEC   UTILITIES
503    XEL   UTILITIES

[504 rows x 2 columns]

In [143]:
dxy_csv = Path("Resources/$dxy_historical_data_01-01_to_09-15-2020.csv")
dxy_df = pd.read_csv(dxy_csv)
dxy_df["ticker"]="DXY"
dxy_df = dxy_df.rename(columns={"Last":"close", "Time":"date"})
dxy_df = dxy_df[["date", "close", "ticker"]].dropna()

In [144]:
btc_csv = Path("Resources/btcusd_historical_data_01-01_to_09-15-2020.csv")
btc_df = pd.read_csv(btc_csv)
btc_df["ticker"]="BTC"
btc_df = btc_df.rename(columns={"Last":"close", "Time":"date"}).dropna()
btc_df = btc_df[["date", "close", "ticker"]]

In [145]:
xau_csv = Path("Resources/btcusd_historical_data_01-01_to_09-15-2020.csv")
xau_df = pd.read_csv(xau_csv)
xau_df["ticker"]="XAU"
xau_df = xau_df.rename(columns={"Last":"close", "Time":"date"}).dropna()
xau_df = xau_df[["date", "close", "ticker"]]

In [146]:
alternative_assets = pd.concat([dxy_df, btc_df, xau_df])
alternative_assets

          date    close ticker
0    9/15/2020    93.07    DXY
1    9/14/2020    93.05    DXY
2    9/11/2020    93.27    DXY
3    9/10/2020    93.34    DXY
4     9/9/2020    93.26    DXY
..         ...      ...    ...
180   1/7/2020  8018.82    XAU
181   1/6/2020  7580.60    XAU
182   1/3/2020  7278.13    XAU
183   1/2/2020  6974.40    XAU
184   1/1/2020  7230.95    XAU

[554 rows x 3 columns]

In [162]:
# Set the ticker to stripes of 100
ticker_list = sectors_df["ticker"].to_list()
ticker_stripe_1 = ticker_list[0:99]
ticker_stripe_2 = ticker_list[99:198]
ticker_stripe_3 = ticker_list[198:297]
ticker_stripe_4 = ticker_list[297:396]
ticker_stripe_5 = ticker_list[396:495]
ticker_stripe_6 = ticker_list[495:]

# Set timeframe to '1D'
timeframe = "1D"

# Set start and end datetimes of from Jan 1 2020 to Sep 15 2020
start_date = start = pd.Timestamp("2020-01-01", tz="America/Chicago").isoformat()
end_date = pd.Timestamp("2020-09-15", tz="America/Chicago").isoformat()

# Chunk the data by stripes to make it compaitible with alpaca api ingestion 

spy_stripe_1 = api.get_barset(
    ticker_stripe_1,
    timeframe,
    start=start_date,
    end=end_date
).df

spy_stripe_2 = api.get_barset(
    ticker_stripe_2,
    timeframe,
    start=start_date,
    end=end_date
).df

spy_stripe_3 = api.get_barset(
    ticker_stripe_3,
    timeframe,
    start=start_date,
    end=end_date
).df

spy_stripe_4 = api.get_barset(
    ticker_stripe_4,
    timeframe,
    start=start_date,
    end=end_date
).df

spy_stripe_5 = api.get_barset(
    ticker_stripe_5,
    timeframe,
    start=start_date,
    end=end_date
).df

spy_stripe_6 = api.get_barset(
    ticker_stripe_6,
    timeframe,
    start=start_date,
    end=end_date
).df

# Combine all of the stripes together 
spy_df = pd.concat([spy_stripe_1, spy_stripe_2, spy_stripe_3, spy_stripe_4, spy_stripe_5, spy_stripe_6], axis=1)
spy_df

                               AAP                                       \
                              open      high       low   close   volume
2020-01-02 00:00:00-05:00  160.470  160.9500  157.5300  159.40   726650
2020-01-03 00:00:00-05:00  158.030  159.6300  157.2500  159.48   482371
2020-01-06 00:00:00-05:00  157.740  158.8900  156.4325  156.82   571689
2020-01-07 00:00:00-05:00  156.900  157.4000  152.4090  154.95  1018841
2020-01-08 00:00:00-05:00  154.850  156.0500  153.1400  153.15   706524
...                            ...       ...       ...     ...      ...
2020-09-09 00:00:00-04:00  152.620  155.6800  152.6200  154.30  1040694
2020-09-10 00:00:00-04:00  154.565  155.4224  153.1050  153.57   641194
2020-09-11 00:00:00-04:00  154.470  155.3200  153.0800  154.56   879257
2020-09-14 00:00:00-04:00  156.900  158.9150  156.1300  157.35  1323752
2020-09-15 00:00:00-04:00  157.890  158.4100  156.5100  156.89   414408

                             ADM                                   ...    WEC  \
                            open    high      low  close   volume  ...   open
2020-01-02 00:00:00-05:00  46.57  46.640  45.8800  46.11  1899517  ...  92.40
2020-01-03 00:00:00-05:00  45.89  46.190  45.7200  46.02  1512616  ...  90.65
2020-01-06 00:00:00-05:00  45.79  45.845  45.3200  45.67  2045946  ...  91.34
2020-01-07 00:00:00-05:00  45.57  45.690  45.1000  45.11  1559273  ...  90.89
2020-01-08 00:00:00-05:00  45.11  45.230  44.3800  44.61  2647364  ...  91.21
...                          ...     ...      ...    ...      ...  ...    ...
2020-09-09 00:00:00-04:00  45.51  46.340  45.4700  46.06  5600146  ...  96.30
2020-09-10 00:00:00-04:00  46.48  46.590  45.9386  46.02  3923889  ...  97.04
2020-09-11 00:00:00-04:00  46.13  46.970  46.0100  46.89  5603942  ...  96.11
2020-09-14 00:00:00-04:00  47.00  47.760  46.9600  47.50  5669474  ...  96.55
2020-09-15 00:00:00-04:00  47.78  47.900  47.2700  47.47  2018791  ...  97.75

                                                                XEL           \
                              high     low  close   volume     open     high
2020-01-02 00:00:00-05:00  92.5200  90.455  90.68  1267002  63.5500  63.5800
2020-01-03 00:00:00-05:00  91.7100  90.520  91.22  1405515  62.2800  62.9150
2020-01-06 00:00:00-05:00  91.8000  90.800  91.34   907752  62.7600  62.9400
2020-01-07 00:00:00-05:00  91.0700  90.340  90.96   929662  62.1500  62.5168
2020-01-08 00:00:00-05:00  91.3850  90.510  91.11   810945  62.5900  62.6400
...                            ...     ...    ...      ...      ...      ...
2020-09-09 00:00:00-04:00  99.0400  95.970  97.76  1872756  69.1400  71.3500
2020-09-10 00:00:00-04:00  97.6700  95.860  95.96  1612510  69.9900  70.6750
2020-09-11 00:00:00-04:00  96.3000  94.930  95.92  1619722  69.2500  69.3500
2020-09-14 00:00:00-04:00  97.7717  95.830  97.14  1182122  68.4268  69.9000
2020-09-15 00:00:00-04:00  99.2800  97.750  99.18   862325  69.8600  71.1500


                               low   close   volume
2020-01-02 00:00:00-05:00  62.2000  62.380  2340833
2020-01-03 00:00:00-05:00  62.2800  62.680  1908930
2020-01-06 00:00:00-05:00  62.3300  62.590  1392103
2020-01-07 00:00:00-05:00  61.9700  62.460  1607021
2020-01-08 00:00:00-05:00  62.1200  62.420  1637440
...                            ...     ...      ...
2020-09-09 00:00:00-04:00  69.1400  70.590  1662544
2020-09-10 00:00:00-04:00  69.0400  69.140  1586323
2020-09-11 00:00:00-04:00  68.1600  68.849  1865467
2020-09-14 00:00:00-04:00  68.3495  69.540  1412411
2020-09-15 00:00:00-04:00  69.8150  70.410  1598371

[178 rows x 2520 columns]

In [169]:
spy_df.to_csv(r'C:\Users\achri\OneDrive\Desktop\FinTech\Homework\stock_indy_500\spy_df_csv.csv', index = True)
spy_df_csv = Path(r'C:\Users\achri\OneDrive\Desktop\FinTech\Homework\stock_indy_500\spy_df_csv.csv')
spy_csv_df = pd.read_csv(spy_df_csv, header=None )
spy_csv_df[0] = pd.to_datetime(spy_csv_df[0], utc=True).dt.date
spy_csv_df

,0,1,2,3,4,5,6,7,8,9,...,2511,2512,2513,2514,2515,2516,2517,2518,2519,2520
0,NaT,AAP,AAP,AAP,AAP,AAP,ADM,ADM,ADM,ADM,...,WEC,WEC,WEC,WEC,WEC,XEL,XEL,XEL,XEL,XEL
1,NaT,open,high,low,close,volume,open,high,low,close,...,open,high,low,close,volume,open,high,low,close,volume
2,2020-01-02,160.47,160.95,157.53,159.4,726650,46.57,46.64,45.88,46.11,...,92.4,92.52,90.455,90.68,1267002,63.55,63.58,62.2,62.38,2340833
3,2020-01-03,158.03,159.63,157.25,159.48,482371,45.89,46.19,45.72,46.02,...,90.65,91.71,90.52,91.22,1405515,62.28,62.915,62.28,62.68,1908930
4,2020-01-06,157.74,158.89,156.4325,156.82,571689,45.79,45.845,45.32,45.67,...,91.34,91.8,90.8,91.34,907752,62.76,62.94,62.33,62.59,1392103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,2020-09-09,152.62,155.68,152.62,154.3,1040694,45.51,46.34,45.47,46.06,...,96.3,99.04,95.97,97.76,1872756,69.14,71.35,69.14,70.59,1662544
176,2020-09-10,154.565,155.4224,153.105,153.57,641194,46.48,46.59,45.9386,46.02,...,97.04,97.67,95.86,95.96,1612510,69.99,70.675,69.04,69.14,1586323
177,2020-09-11,154.47,155.32,153.08,154.56,879257,46.13,46.97,46.01,46.89,...,96.11,96.3,94.93,95.92,1619722,69.25,69.35,68.16,68.849,1865467
178,2020-09-14,156.9,158.915,156.13,157.35,1323752,47.0,47.76,46.96,47.5,...,96.55,97.7717,95.83,97.14,1182122,68.4268,69.9,68.3495,69.54,1412411
179,2020-09-15,157.89,158.41,156.51,156.89,414408,47.78,47.9,47.27,47.47,...,97.75,99.28,97.75,99.18,862325,69.86,71.15,69.815,70.41,1598371

In [170]:
#new_header = spy_csv_df.iloc[0] #grab the first row for the header
#spy_csv_df = spy_csv_df[1:] #take the data less the header row
#spy_csv_df.columns = new_header #set the header row as the df header

header_row= 1
spy_csv_df.columns = spy_csv_df.iloc[header_row]
spy_csv_df
#spy_csv_df.drop(['open', 'high', 'low', 'volume'], axis=1, inplace=True)
#spy_csv_df

1,NaN,open,high,low,close,volume,open,high,low,close,...,open,high,low,close,volume,open,high,low,close,volume
0,NaT,AAP,AAP,AAP,AAP,AAP,ADM,ADM,ADM,ADM,...,WEC,WEC,WEC,WEC,WEC,XEL,XEL,XEL,XEL,XEL
1,NaT,open,high,low,close,volume,open,high,low,close,...,open,high,low,close,volume,open,high,low,close,volume
2,2020-01-02,160.47,160.95,157.53,159.4,726650,46.57,46.64,45.88,46.11,...,92.4,92.52,90.455,90.68,1267002,63.55,63.58,62.2,62.38,2340833
3,2020-01-03,158.03,159.63,157.25,159.48,482371,45.89,46.19,45.72,46.02,...,90.65,91.71,90.52,91.22,1405515,62.28,62.915,62.28,62.68,1908930
4,2020-01-06,157.74,158.89,156.4325,156.82,571689,45.79,45.845,45.32,45.67,...,91.34,91.8,90.8,91.34,907752,62.76,62.94,62.33,62.59,1392103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,2020-09-09,152.62,155.68,152.62,154.3,1040694,45.51,46.34,45.47,46.06,...,96.3,99.04,95.97,97.76,1872756,69.14,71.35,69.14,70.59,1662544
176,2020-09-10,154.565,155.4224,153.105,153.57,641194,46.48,46.59,45.9386,46.02,...,97.04,97.67,95.86,95.96,1612510,69.99,70.675,69.04,69.14,1586323
177,2020-09-11,154.47,155.32,153.08,154.56,879257,46.13,46.97,46.01,46.89,...,96.11,96.3,94.93,95.92,1619722,69.25,69.35,68.16,68.849,1865467
178,2020-09-14,156.9,158.915,156.13,157.35,1323752,47.0,47.76,46.96,47.5,...,96.55,97.7717,95.83,97.14,1182122,68.4268,69.9,68.3495,69.54,1412411
179,2020-09-15,157.89,158.41,156.51,156.89,414408,47.78,47.9,47.27,47.47,...,97.75,99.28,97.75,99.18,862325,69.86,71.15,69.815,70.41,1598371

In [171]:
spy_csv_df.drop(['open', 'high', 'low', 'volume'], axis=1, inplace=True)
spy_csv_df.rename({'NaN':'Date'})

1,NaN,close,close,close,close,close,close,close,close,close,...,close,close,close,close,close,close,close,close,close,close
0,NaT,AAP,ADM,AMZN,APTV,ATVI,AZO,BBY,BKNG,BWA,...,ZBRA,NI,NRG,PEG,PNW,PPL,SO,SRE,WEC,XEL
1,NaT,close,close,close,close,close,close,close,close,close,...,close,close,close,close,close,close,close,close,close,close
2,2020-01-02,159.4,46.11,1897.71,96.33,58.64,1187.75,87.32,2074.31,43.95,...,259.14,27.19,38.8,58.7,88.7,35.41,62.63,149.13,90.68,62.38
3,2020-01-03,159.48,46.02,1874.93,94.06,58.67,1187.74,87.16,2065.89,42.35,...,256.1,27.39,38.19,58.69,88.98,35.37,62.53,147.76,91.22,62.68
4,2020-01-06,156.82,45.67,1903.33,92.34,59.75,1165.49,87.92,2046.59,42.17,...,258.01,27.4,37.37,58.15,88.91,35.41,62.81,149.01,91.34,62.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,2020-09-09,154.3,46.06,3268.27,85.61,79.58,1232.38,108.85,1872.84,42.29,...,255.12,22.12,32.37,53.44,72.63,27.74,52.85,120.96,97.76,70.59
176,2020-09-10,153.57,46.02,3176.12,84.09,79.1,1217.64,107.37,1819.12,41.67,...,249.46,21.88,31.38,52.29,71.39,27.28,51.55,118.09,95.96,69.14
177,2020-09-11,154.56,46.89,3117.28,84.53,77.95,1233.53,107.15,1781.23,42.37,...,249.96,22.05,31.6,52.4,70.9,27.53,51.76,117.8,95.92,68.849
178,2020-09-14,157.35,47.5,3102.97,85.9,79.13,1241.91,107.69,1782.635,42.81,...,251.19,22.39,31.53,52.48,72.07,27.91,52.87,119.12,97.14,69.54
179,2020-09-15,156.89,47.47,3153.28,85.99,81.8,1242.95,107.98,1786.46,42.28,...,257.49,22.11,30.59,51.66,72.02,27.71,53.01,117.55,99.18,70.41

In [151]:
header_row= 0
spy_csv_df.columns = spy_csv_df.iloc[header_row]
spy_csv_df

,NaN,AAP,ADM,AMZN,APTV,ATVI,AZO,BBY,BKNG,BWA,...,ZBRA,NI,NRG,PEG,PNW,PPL,SO,SRE,WEC,XEL
0,NaT,AAP,ADM,AMZN,APTV,ATVI,AZO,BBY,BKNG,BWA,...,ZBRA,NI,NRG,PEG,PNW,PPL,SO,SRE,WEC,XEL
1,NaT,close,close,close,close,close,close,close,close,close,...,close,close,close,close,close,close,close,close,close,close
2,2020-01-02,159.4,46.11,1897.71,96.33,58.64,1187.75,87.32,2074.31,43.95,...,259.14,27.19,38.8,58.7,88.7,35.41,62.63,149.13,90.68,62.38
3,2020-01-03,159.48,46.02,1874.93,94.06,58.67,1187.74,87.16,2065.89,42.35,...,256.1,27.39,38.19,58.69,88.98,35.37,62.53,147.76,91.22,62.68
4,2020-01-06,156.82,45.67,1903.33,92.34,59.75,1165.49,87.92,2046.59,42.17,...,258.01,27.4,37.37,58.15,88.91,35.41,62.81,149.01,91.34,62.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,2020-09-09,154.3,46.06,3268.27,85.61,79.58,1232.38,108.85,1872.84,42.29,...,255.12,22.12,32.37,53.44,72.63,27.74,52.85,120.96,97.76,70.59
176,2020-09-10,153.57,46.02,3176.12,84.09,79.1,1217.64,107.37,1819.12,41.67,...,249.46,21.88,31.38,52.29,71.39,27.28,51.55,118.09,95.96,69.14
177,2020-09-11,154.56,46.89,3117.28,84.53,77.95,1233.53,107.15,1781.23,42.37,...,249.96,22.05,31.6,52.4,70.9,27.53,51.76,117.8,95.92,68.849
178,2020-09-14,157.35,47.5,3102.97,85.9,79.13,1241.91,107.69,1782.635,42.81,...,251.19,22.39,31.53,52.48,72.07,27.91,52.87,119.12,97.14,69.54
179,2020-09-15,156.89,47.47,3153.28,85.99,81.8,1242.95,107.98,1786.46,42.28,...,257.49,22.11,30.59,51.66,72.02,27.71,53.01,117.55,99.18,70.41

In [153]:
spy_csv_df= spy_csv_df[2:]
spy_csv_df

,NaN,AAP,ADM,AMZN,APTV,ATVI,AZO,BBY,BKNG,BWA,...,ZBRA,NI,NRG,PEG,PNW,PPL,SO,SRE,WEC,XEL
5,2020-01-07,154.95,45.11,1906.86,91.21,60.335,1145.49,88.41,2067.8,42.44,...,256.47,27.635,36.87,57.64,88.67,35.17,62.62,148.88,90.96,62.46
6,2020-01-08,153.15,44.61,1892.09,93.09,59.87,1147.22,88.6,2062.54,42.7,...,247.63,27.67,36.86,57.95,88.52,35.39,62.62,149.89,91.11,62.42
7,2020-01-09,152.88,44.15,1901.0,91.75,59.34,1146.29,89.37,2085.43,41.94,...,246.5,27.74,37.14,58.4,89.89,35.5,63.26,148.87,91.99,62.54
8,2020-01-10,149.0,43.945,1882.98,89.49,58.95,1132.09,90.65,2086.9,41.41,...,246.26,27.63,37.32,58.3,90.57,35.44,63.665,149.76,92.54,62.64
9,2020-01-13,145.29,44.43,1891.41,88.86,59.24,1128.6,91.25,2080.05,41.38,...,248.58,27.88,36.92,58.25,91.26,35.44,64.54,151.17,93.67,63.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,2020-09-09,154.3,46.06,3268.27,85.61,79.58,1232.38,108.85,1872.84,42.29,...,255.12,22.12,32.37,53.44,72.63,27.74,52.85,120.96,97.76,70.59
176,2020-09-10,153.57,46.02,3176.12,84.09,79.1,1217.64,107.37,1819.12,41.67,...,249.46,21.88,31.38,52.29,71.39,27.28,51.55,118.09,95.96,69.14
177,2020-09-11,154.56,46.89,3117.28,84.53,77.95,1233.53,107.15,1781.23,42.37,...,249.96,22.05,31.6,52.4,70.9,27.53,51.76,117.8,95.92,68.849
178,2020-09-14,157.35,47.5,3102.97,85.9,79.13,1241.91,107.69,1782.635,42.81,...,251.19,22.39,31.53,52.48,72.07,27.91,52.87,119.12,97.14,69.54
179,2020-09-15,156.89,47.47,3153.28,85.99,81.8,1242.95,107.98,1786.46,42.28,...,257.49,22.11,30.59,51.66,72.02,27.71,53.01,117.55,99.18,70.41

In [160]:
column_headers = spy_csv_df.columns
column_headers = column_headers[1:]
spy_csv_df.pivot(index=spy_csv_df['NaN'], columns=column_headers)

KeyError: 'NaN'